### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by Eggmanplant** [MegAmi24/Pong-GameAPI#1]
`[ 14%] Building CXX object CMakeFiles/PongGameAPI.dir/Source/GameAPI/CPP/GameAPI/Game.cpp.o
[ 28%] Building CXX object CMakeFiles/PongGameAPI.dir/Source/PongGameAPI/PongGameAPI.cpp.o
[ 42%] Building CXX object CMakeFiles/PongGameAPI.dir/Source/PongGameAPI/Objects/Pong/Ball.cpp.o
[ 57%] Building CXX object CMakeFiles/PongGameAPI.dir/Source/PongGameAPI/Objects/Pong/HUD.cpp.o
[ 71%] Building CXX object CMakeFiles/PongGameAPI.dir/Source/PongGameAPI/Objects/Pong/Paddle.cpp.o
In file included from /home/builds/Pong-GameAPI/Source/GameAPI/CPP/GameAPI/RSDKv5/RSDKv5.hpp:19,
                 from /home/builds/Pong-GameAPI/Source/GameAPI/CPP/GameAPI/Game.hpp:108,
                 from /home/builds/Pong-GameAPI/Source/PongGameAPI/PongGameAPI.hpp:3,
                 from /home/builds/Pong-GameAPI/Source/PongGameAPI/Objects/Pong/Paddle.hpp:3,
                 from /home/builds/Pong-GameAPI/Source/PongGameAPI/Objects/Pong/Paddle.cpp:7:
/home/builds/Pong-GameAPI/Source/GameAPI/CPP/GameAPI/RSDKv5/Game/StateMachine.hpp: In instantiation of 'void RSDK::StateMachine<T>::Run(RSDK::GameObject::Entity*) [with T = GameLogic::Paddle]':
/home/builds/Pong-GameAPI/Source/PongGameAPI/Objects/Pong/Paddle.cpp:19:25:   required from here
/home/builds/Pong-GameAPI/Source/GameAPI/CPP/GameAPI/RSDKv5/Game/StateMachine.hpp:137:72: error: invalid conversion from 'void (*)()' to 'void*' [-fpermissive]
  137 |             bool32 skipState = modTable->HandleRunState_HighPriority(u.out);
      |                                                                      ~~^~~
      |                                                                        |
      |                                                                        void (*)()
/home/builds/Pong-GameAPI/Source/GameAPI/CPP/GameAPI/RSDKv5/Game/StateMachine.hpp:142:52: error: invalid conversion from 'void (*)()' to 'void*' [-fpermissive]
  142 |             modTable->HandleRunState_LowPriority(u.out, skipState);
      |                                                  ~~^~~
      |                                                    |
      |                                                    void (*)()
make[2]: *** [CMakeFiles/PongGameAPI.dir/build.make:132: CMakeFiles/PongGameAPI.dir/Source/PongGameAPI/Objects/Pong/Paddle.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/PongGameAPI.dir/all] Error 2
make: *** [Makefile:91: all] Error 2`
OS: Void Linux

**Comment by MegAmi24** [comment]
Looks like an issue with running StateMachines? Most likely an issue with GameAPI rather than Pong, but I'll keep this issue open as I look into it.

**Comment by MegAmi24** [comment]
Can confirm that this is a GameAPI issue, see RSDKModding/RSDKv5-GameAPI#12.
I'll be closing this issue since it's not Pong specific, but as a workaround, try using the `-fpermissive` flag when building to report errors as warnings instead.

**Comment by MegAmi24** [comment]
A workaround to the issue has been added to GameAPI and I've updated the submodule. The mod should build normally now.
